import type { StrategyConfig } from "./types";

export const defaultConfig: StrategyConfig = {
  symbol: process.env.TRADER_SYMBOL ?? "GOLD.i#",
  direction: "both",
  gridType: "points",
  gridDistance: 1,
  maxLegs: 8,
  legs: Array.from({ length: 8 }, () => ({ enabled: true, lotSize: 0.01 })),
  lotMode: "fixed",
  lotSize: 0.01,
  multiplier: 1.5,
  riskPercent: 1,
  individualTakeProfit: 1,
  basketTakeProfit: 50,
  trailingBasketTakeProfit: 0,
  stopLoss: 0,
  basketStopLoss: 100,
  dailyDrawdown: 5,
  maxExposure: 1,
  maxLots: 1,
  tradingStartTime: "00:00",
  tradingEndTime: "23:20",
  forceExitTime: "23:30",
  forceExitEnabled: true,
  forceExitType: "hybrid",
  entryCutoffTime: "23:20",
  enableReEntry: true,
  enableNewsFilter: false,
  enableFridayExit: true,
  enableSpreadFilter: true,
  maxSpread: 2,
  enableCooldown: true,
  cooldownMinutes: 30,
  resetOnNewHighLow: true,
  maxReEntriesPerLevel: 999,
  newHighLowMode: "reset"
};
